export { HomePage } from './home-page'
export { AboutPage } from './about-page'
export { DashboardPage } from './dashboard-page'
export { LoginPage } from './login-page'
export { RegisterPage } from './register-page'
